### ISSUE TITLE
readme didn't quite work for me

### ISSUE THREAD

**Issue by jovo** [zhoupc/OASIS_matlab#1]
`>> run examples/paper/fig*.m

Error using run (line 72)
RUN cannot execute the file 'examples/paper/fig*.m'. RUN requires a valid MATLAB script`

`run examples/Paper/test_all.m`

did work.

i'm using matbal R2016b

**Comment by zhoupc** [comment]
sorry for the confusion, you have to replace * with a number, for example 
run examples/Paper/fig1.m
