### ISSUE TITLE
oasisAR1 output with unexpected size

### ISSUE THREAD

**Issue by JDechery** [zhoupc/OASIS_matlab#2]
If oasisAR1.m is called with an empty array as the first argument, as in constrained_oasisAR1; line 179:
`[solution, spks, active_set] = oasisAR1([], g, lam, [], active_set);`

then the second output variable, _s_, may not have the same size as _c_.
Specifically, it will have _active_set(end)_-1 fewer elements than _c_.

A quick workaround is to modify lines 92-93 of oasisAR1.m to
`len_y = sum(active_set(end,3:4))-1;`
`c = zeros(1,len_y);`
`s = zeros(1,len_y);`

**Comment by zhoupc** [comment]
@JDechery nice catch. fixed. thanks.
