### ISSUE TITLE
estimate_time_constant typo and missing variables

### ISSUE THREAD

**Issue by ClaudiaEF** [zhoupc/OASIS_matlab#3]
Hello!

I've already discussed this topic with Johannes, but he said the matlab code is not identical to the python one, so here goes the issue:

I encountered a problem with some of my data -- when in ' estimate time constant.m'  cannot find a good model, the software crashes here:
while max(abs(roots([1,-g(:)']))>1) && p < 5
% warning('No stable AR(%i) model found. Checking for AR(%i) model \n',options.p,options.p+1);
p = p + 1;
g = estimate_time_constants(y,p,sn,lags);
end

because it cannot find 'options', but also because estimate_time_constants is not available in the package I downloaded (I guess this is a typo and it's calling itself again?).
Thanks

CLaudia

**Comment by zhoupc** [comment]
@claudiaFF Thanks for pointing it out. it's a typo. I updated the code to estimate_time_constant.
